# Generated by Django 4.0.2 on 2022-02-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0004_task_listof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
